version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    environment:
      OPEN_AI_KEY: ${OPEN_AI_KEY}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_URI: ${TELEGRAM_BOT_URI}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AMO_CRM_API_KEY: ${AMO_CRM_API_KEY}
      AMO_CRM_API_URL: ${AMO_CRM_API_URL}
      CHAT_GPT_FILES: ${CHAT_GPT_FILES}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge